### ISSUE TITLE
is there any initialize function?

### ISSUE THREAD

**Issue by crazyfireji** [smillerc/MPIHaloArrays.jl#8]
Is there a function that reads a 3 dimensional array from process 1 and sends specific block to another process

**Comment by crazyfireji** [comment]
i use this code, but can't works
'if rank == root
	f1=FortranFile("u.dat","r") 
		read(f1,SA)
	close(f1)
	A = scatterglobal(SA, root, nhalo, topology; 
                   do_corners = true)
end
'
i read sa in procs 0 since sa is very big.

**Comment by smillerc** [comment]
Can you post a full example with error messages? It's difficult to determine what went wrong without more detail.

**Comment by crazyfireji** [comment]
`# examples/03-halo3d.jl
using MPI, MPIHaloArrays
using OffsetArrays
using FortranFiles

MPI.Init()
const comm = MPI.COMM_WORLD
const rank = MPI.Comm_rank(comm)
const nprocs = MPI.Comm_size(comm)
const root = 0 # root rank
global PRECISION = Float32

@assert nprocs == 8 "This example is designed with 8 processes..."

function initializer3D(filename, nx0,ny0, nz0,
	topology::AbstractParallelTopology; halo_dims = (1, 2, 3))

    U=zeros(PRECISION,nx0,ny0,nz0);
	U0=zeros(PRECISION,nx0,ny0)
    for k in 1:nz0
		read(filename, U0)
		U[:,:,k] .= 3.14#U0
	end	
	
	#display(U[10,1:165,10])
    halo_dims = (1, 2, 3)

    global_domain_size = size(topology)
    
    sizes = MPIHaloArrays.get_subdomain_sizes(size(U), global_domain_size, halo_dims) 
    
    indices = MPIHaloArrays.get_subdomain_indices(size(U), global_domain_size, halo_dims)
    
    for sendrank in 0:topology.nprocs-1

        # Get the indices on the root buffer to send to the remote buffer
        ilo, ihi, jlo, jhi, klo, khi = indices[sendrank + 1]
        #@show sendrank, (ilo, ihi, jlo, jhi, klo, khi)
        data_on_root = @view U[ilo:ihi, jlo:jhi, klo:khi]
        root_buf = MPI.Buffer(data_on_root)
        sendtag = sendrank + 1000
        sreq =  MPI.Isend(root_buf, sendrank, sendtag, topology.comm)
        push!(reqs, sreq)
    end

	GC.gc()
	
end

npx0=2; 
npy0=2; 
npz0=2;  

nx_global=3072
ny_global=230
nz_global=37

nx=fld(nx_global,npx0)
ny=fld(ny_global,npy0)
nz=fld(nz_global,npz0)

u = zeros(PRECISION, nx, ny, nz)

Lap = 1

topology = CartesianTopology(comm, [npx0,npz0,npy0], [false,false,false])
	
recvbuf = zeros(PRECISION, nx, ny, nz)

reqs = Vector{MPI.Request}(undef, 0)

if topology.rank == root 
	f1=FortranFile("./Re950-8pi3pi/Re950.030u.dat","r") 
	@time initializer3D(f1, nx_global,ny_global,nz_global,topology)
	close(f1)
end
	
recvtag=topology.rank+1000
	
rreq=MPI.Irecv!(recvbuf, root, recvtag, topology.comm)
	
push!(reqs, rreq)

MPI.Waitall!(reqs)

u .= recvbuf

A = MPIHaloArray(u, topology, Lap; do_corners=false)
#==#
#A = scatterglobal(fill!(zeros(nx_global,nz_global,ny_global),rank), root, Lap, topology; 
#                   do_corners = true)

fillhalo!(A, -1)

updatehalo!(A)

G=gatherglobal(A)

if rank == 0 display(G[1:10,5:15,10]) end

GC.gc()

MPI.Finalize()`

**Comment by smillerc** [comment]
Ok, thanks. I'll look into it. When posting code, make sure to surround it in triple ticks, e.g. ```julia

Since I don't have the file you do, what error messages do you get?

**Comment by crazyfireji** [comment]
same question and set, but different npx0,npy0,npz0 will effect its feasibility. for example, npx0=2,npy0=2,npz0  =2 can work sometimes , but can't work when npx=1, npy=2,npz=4

**Comment by crazyfireji** [comment]
> 

the file don't need, i set u=3.14， this is error message 
/
![-fd10b5dfb6a442b](https://user-images.githubusercontent.com/112403698/234881092-13f974fa-ad1a-47c6-a4cc-7f3b84ac13f3.png)

/

**Comment by crazyfireji** [comment]
Sorry, it works, it exists a mistake in my code

**Comment by smillerc** [comment]
Ok, thanks! Glad everything is working for you
